import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SnapScroll from '@/components/SnapScroll/SnapScroll'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SnapScroll>
          <section style={{backgroundColor: 'rgb(66, 165, 241)'}}>
            <h1>section 1</h1>
          </section>
          <section style={{backgroundColor: 'rgb(36, 196, 143)'}}>
            <h1>section 2</h1>
          </section>
          <section style={{backgroundColor: 'coral'}}>
            <h1>section 3</h1>
          </section>
          <section style={{backgroundColor: 'rgb(163, 76, 206)'}}>
            <h1>section 4</h1>
          </section>
        </SnapScroll>
      </main>
    </>
  )
}
